version: '3.9'

services:
  activemq:
    image: symptoma/activemq:latest
#    container_name: ‘activemq’
    ports:
      - '61616:61616'
      - '8161:8161'
    volumes:
      - ./src/main/resources/activemq/data:/data/activemq
      - ./src/main/resources/activemq/log:/var/log/activemq